# -----------------------------------------------------
# Langing Page Theme Configurations
cover_images:
  - /img/AdobeStock_159597945-poster-00001.jpg
  - /img/intro-bg.jpg
  - /img/about.jpg
  - /img/cat-bg.jpg
  - /img/contact-bg.jpg
  - /img/home-bg.jpg
  - /img/home-bg-o.jpg

banner_image: /img/banner-bg.jpg

# Navigation items
navigation:
  So funktioniert es: '#astro'
  Für wen ist es geignet und für wen nicht: '#fuer'
  Leistungen: '#leistungen'
  Über mich: '#uebermich'
  Kontakt: '#kontakt'

social:
  # - title: zhihu
  #   url: https://www.zhihu.com/people/frostming
  # - title: github
  #   url: https://github.com/frostming/
  # - title: linkedin
  #   url: https://www.linkedin.com/in/%E5%B8%8C-%E6%98%8E-33452ba2
  # - title: weibo
  #   url: http://weibo.com/frostanne
# Duoshuo comments & share
# duoshuo_shortname: frostming
# Disqus
# disqus_shortname:

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
